version: "3.9"
services:
  keycloak:
    build: .
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=kc_username
      - KEYCLOAK_ADMIN_PASSWORD=kc_password
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HEALTH_ENABLED=true
      - KC_LOG_LEVEL=INFO,cz.integsoft:DEBUG,org.infinispan:DEBUG,org.jgroups:DEBUG
      - KC_DB=mariadb
      - KC_DB_URL_HOST=mariadb
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_URL_PROPERTIES=?autoReconnect=true
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_CACHE_CONFIG_FILE=cache-ispn-jdbc-ping.xml
      - JAVA_OPTS_APPEND=-Xmx1500m -Djboss.bind.address=0.0.0.0
      - AWS_REGION=us-east-1
    links:
      - mariadb
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_USER=keycloak
      - MARIADB_PASSWORD=keycloak
      - MARIADB_DATABASE=keycloak
      - MARIADB_RANDOM_ROOT_PASSWORD=true
