name: Build Container Image

on:
  push:
    tags:
      - '*'

jobs:
  build-image:
    name: Build Container Image
    runs-on: ubuntu-latest
    concurrency: build-image
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Get pushed tag name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: mbta/actions/build-push-ecr@v2
        id: build-push
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          docker-repo: ${{ secrets.DOCKER_REPO }}
          docker-additional-tags: ${{ steps.vars.outputs.tag }}
