name: Deploy Keycloak Staging

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Existing Tag to Deploy'
        required: true

permissions:
  contents: read # private repo, needs permission to read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: Keycloak Staging
      url: https://login-staging.mbtace.com/
    concurrency: staging
    env:
      ECS_CLUSTER: keycloak
      ECS_SERVICE: keycloak-staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: mbta/actions/build-push-ecr@d37877022d4ae12e96663d2e0a970a5214a2e232 # v2.20
        permissions:
          id-token: write # needed to push tags
        id: build-push
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          docker-repo: ${{ secrets.DOCKER_REPO }}
          docker-additional-tags: staging
      - uses: mbta/actions/deploy-ecs@d37877022d4ae12e96663d2e0a970a5214a2e232 # v2.20
        permissions:
          id-token: write # needed to push tags
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          ecs-cluster: ${{ env.ECS_CLUSTER }}
          ecs-service: ${{ env.ECS_SERVICE }}
          docker-tag: ${{ secrets.DOCKER_REPO }}:${{ github.event.inputs.tag }}      
      - uses: mbta/actions/notify-slack-deploy@d37877022d4ae12e96663d2e0a970a5214a2e232 # v2.20
        permissions:
          id-token: write # needed for slack
        if: ${{ !cancelled() }}
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          job-status: ${{ job.status }}
