name: Deploy Keycloak Staging

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Existing Tag to Deploy'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: Keycloak Staging
      url: https://login-staging.mbtace.com/
    concurrency: staging
    env:
      ECS_CLUSTER: keycloak
      ECS_SERVICE: keycloak-staging

    steps:
      - uses: actions/checkout@v2
      - uses: mbta/actions/build-push-ecr@v2
        id: build-push
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          docker-repo: ${{ secrets.DOCKER_REPO }}
          docker-additional-tags: staging
      - uses: mbta/actions/deploy-ecs@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          ecs-cluster: ${{ env.ECS_CLUSTER }}
          ecs-service: ${{ env.ECS_SERVICE }}
          docker-tag: ${{ secrets.DOCKER_REPO }}:${{ github.event.inputs.tag }}      
      - uses: mbta/actions/notify-slack-deploy@v1
        if: ${{ !cancelled() }}
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          job-status: ${{ job.status }}
